//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Resource
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Resource()
    {
        this.ResourceClick = new HashSet<ResourceClick>();
        this.ResourceGroupTotalClick = new HashSet<ResourceGroupTotalClick>();
        this.ResourceLink = new HashSet<ResourceLink>();
        this.SearchKey = new HashSet<SearchKey>();
    }

    public string ResourceId { get; set; }
    public string ResourceTitle { get; set; }
    public string Description { get; set; }
    public string ResourceSubGroupId { get; set; }
    public Nullable<int> TotalClick { get; set; }

    public virtual ResourceSubGroup ResourceSubGroup { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceClick> ResourceClick { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceGroupTotalClick> ResourceGroupTotalClick { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceLink> ResourceLink { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SearchKey> SearchKey { get; set; }
}

public partial class ResourceClick
{
    public string ResouceId { get; set; }
    public Nullable<long> ResourceClick1 { get; set; }
    public int ClickDate { get; set; }

    public virtual Resource Resource { get; set; }
}

public partial class ResourceGroup
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ResourceGroup()
    {
        this.ResourceSubGroup = new HashSet<ResourceSubGroup>();
    }

    public string ResourceGroupId { get; set; }
    public string ResourceGroupName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceSubGroup> ResourceSubGroup { get; set; }
}

public partial class ResourceGroupTotalClick
{
    public string ResourceId { get; set; }
    public string ResourceGoupId { get; set; }
    public Nullable<long> GroupTotalClick { get; set; }

    public virtual Resource Resource { get; set; }
}

public partial class ResourceLink
{
    public string ResourceId { get; set; }
    public string SourceId { get; set; }
    public string Link { get; set; }
    public string ResourceCode { get; set; }
    public string Remark { get; set; }

    public virtual Resource Resource { get; set; }
    public virtual Source Source { get; set; }
}

public partial class ResourceSubGroup
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ResourceSubGroup()
    {
        this.Resource = new HashSet<Resource>();
    }

    public string ResourceSubGroupId { get; set; }
    public string ResourceGroupId { get; set; }
    public string ResourceSubGroupName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resource> Resource { get; set; }
    public virtual ResourceGroup ResourceGroup { get; set; }
}

public partial class SearchKey
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SearchKey()
    {
        this.Resource = new HashSet<Resource>();
    }

    public int SearchKeyId { get; set; }
    public string SearchKeyText { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resource> Resource { get; set; }
}

public partial class Source
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Source()
    {
        this.ResourceLink = new HashSet<ResourceLink>();
    }

    public string SourceId { get; set; }
    public int Pos { get; set; }
    public string SourceName { get; set; }
    public string Status { get; set; }
    public string IsPrimary { get; set; }
    public string IsDefault { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ResourceLink> ResourceLink { get; set; }
}
